# Render Blueprint for Next.js + GenKit integrated deployment
services:
  - type: web
    name: assistive-seeing-eyes
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon # Recommended for better latency (adjust as needed)
    plan: free # Upgrade to 'starter' or higher for production
    
    # Environment Configuration
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GENKIT_PORT
        value: 3400
      - key: NEXT_PUBLIC_GENKIT_API_BASE_URL
        value: /genkit-api
      - key: NEXT_PUBLIC_GOOGLE_APPLICATION_CREDENTIALS
        sync: false # Set in Render dashboard
      - key: GOOGLE_API_KEY
        sync: false
      - key: GENKIT_PROJECT_ID
        sync: false
    
    # Network Configuration
    httpPort: 3000
    healthCheckPath: /api/health
    autoDeploy: true
    
    # Proxy Rules for Integrated Deployment
    rewrites:
      - source: /genkit-api/(.*)
        destination: http://localhost:3400/$1
        stripPath: true
    
    # Resource Allocation (adjust based on needs)
    resources:
      cpu: 0.25 # Shared
      memoryGB: 0.5 # 512MB - upgrade for production
      swapSizeMB: 512
    
    # Advanced Options
    buildCommand: npm install && npm run build
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 # For persistent storage if needed

# Uncomment if using separate GenKit service:
#  - type: web
#    name: genkit-service
#    runtime: docker
#    dockerfilePath: ./Dockerfile
#    envVars:
#      - key: NODE_ENV
#        value: production
#      - key: PORT
#        value: 3400
#    command: npm run genkit:prod
#    httpPort: 3400
