# Render Blueprint for Next.js + GenKit integrated deployment
services:
  - type: web
    name: assistive-seeing-eyes
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon # Adjust based on user location
    plan: free # Upgrade to 'starter' for production

    # Environment Configuration
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GENKIT_PORT
        value: 3400
      - key: NEXT_PUBLIC_GENKIT_API_BASE_URL
        value: /genkit-api
      - key: NEXT_PUBLIC_GOOGLE_APPLICATION_CREDENTIALS
        sync: false # Set in Render dashboard (e.g., /data/credentials.json)
      - key: GOOGLE_API_KEY
        sync: false # Set in Render dashboard
      - key: GENKIT_PROJECT_ID
        sync: false # Set in Render dashboard

    # Network Configuration
    httpPort: 3000
    healthCheckPath: /api/health
    autoDeploy: true

    # Proxy Rules for Integrated Deployment
    rewrites:
      - source: /genkit-api/(.*)
        destination: http://localhost:3400/$1
        stripPath: true

    # Resource Allocation (upgrade for production)
    resources:
      cpu: 0.25 # Consider 0.5 for starter plan
      memoryGB: 0.5 # Consider 1GB for starter plan
      swapSizeMB: 512

    # Build and Disk
    buildCommand: npm install && npm run build
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 # Remove if not needed
