# Render Blueprint for Next.js + Genkit integrated deployment
services:
  - type: web
    name: assistive-seeing-eyes
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon # Adjust based on user location (e.g., frankfurt, singapore)
    plan: free # Upgrade to 'starter' for production (0.5 CPU, 1GB RAM)

    # Environment Configuration
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GENKIT_PORT
        value: 3400
      - key: NEXT_PUBLIC_GENKIT_API_BASE_URL
        value: /genkit-api
      - key: NEXT_PUBLIC_GOOGLE_APPLICATION_CREDENTIALS
        sync: false # Set in Render dashboard (e.g., JSON content)
      - key: GOOGLE_API_KEY
        sync: false # Set in Render dashboard
      - key: GENKIT_PROJECT_ID
        sync: false # Set in Render dashboard

    autoDeploy: true

    ports:
      - port: 3000  # Next.js app
      - port: 3400  # Genkit dev server
